### ISSUE TITLE
建议：弹幕字体增添是否粗体的选项，并改进阴影样式的CSS

### ISSUE THREAD

**Issue by wuqiling97** [esterTion/AcFun-HTML5-Player#44]
个人感觉粗体比较挡视频内容，所以希望能够增添这一选项。

阴影样式的CSS建议模仿b站的“重墨样式”，增加blur，改为

```css
.ABP-Unit .ABP-Video .ABP-Container .cmt.shadow{
	text-shadow:1px 0px 1px #000, 0px 1px 1px #000, 0px -1px 1px #000, -1px 0px 1px #000;
}
```
这样在文字拐角地方的阴影会看起来比较自然。下图为修改前后的弹幕截图

![改进前](https://user-images.githubusercontent.com/19304928/50089497-f4d0d500-0240-11e9-8992-df3efc9d9c25.png)

![改进后](https://user-images.githubusercontent.com/19304928/50089567-1cc03880-0241-11e9-81e3-6a495366c521.png)
